// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSJrSKjRYSvl0mNDiGoXGa7j1TTfUATnM',
    appId: '1:745600069358:web:9cf2d3d128b85863eb8dff',
    messagingSenderId: '745600069358',
    projectId: 'products-app-5af04',
    authDomain: 'products-app-5af04.firebaseapp.com',
    databaseURL: 'https://products-app-5af04-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'products-app-5af04.appspot.com',
    measurementId: 'G-S7CY9XX0KP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJg6UVwMBYlHeCaYriwYXrgX2dEvy848Y',
    appId: '1:745600069358:android:fed00de583b2acdceb8dff',
    messagingSenderId: '745600069358',
    projectId: 'products-app-5af04',
    databaseURL: 'https://products-app-5af04-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'products-app-5af04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJVpjJoBLckUhQAG-132cVFL7ueyKN4xE',
    appId: '1:745600069358:ios:8880325182b314c2eb8dff',
    messagingSenderId: '745600069358',
    projectId: 'products-app-5af04',
    databaseURL: 'https://products-app-5af04-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'products-app-5af04.appspot.com',
    androidClientId: '745600069358-vpotap2dkhu1qnrgi6rd2qduk3vtjslf.apps.googleusercontent.com',
    iosClientId: '745600069358-2rbavjhhj4k6n1qm3cdsg9ju5qm7g4ru.apps.googleusercontent.com',
    iosBundleId: 'com.example.eComerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJVpjJoBLckUhQAG-132cVFL7ueyKN4xE',
    appId: '1:745600069358:ios:72d9829bc8f00316eb8dff',
    messagingSenderId: '745600069358',
    projectId: 'products-app-5af04',
    databaseURL: 'https://products-app-5af04-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'products-app-5af04.appspot.com',
    androidClientId: '745600069358-vpotap2dkhu1qnrgi6rd2qduk3vtjslf.apps.googleusercontent.com',
    iosClientId: '745600069358-if134r5qah01724tgam0qbvcf5f76vsd.apps.googleusercontent.com',
    iosBundleId: 'com.example.eComerceApp.RunnerTests',
  );
}
